// Mocks generated by Mockito 5.4.5 from annotations
// in frontend/test/unit/providers/prefix_tree_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend/generated/api/lib/api.dart' as _i2;
import 'package:http/http.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1 extends _i1.SmartFake implements _i3.Response {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PrefixTreeApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrefixTreeApi extends _i1.Mock implements _i2.PrefixTreeApi {
  MockPrefixTreeApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakeApiClient_0(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i2.ApiClient);

  @override
  _i4.Future<_i3.Response>
      getPrefixNamesApiV1PrefixTreeNamesPrefixGetWithHttpInfo(
    String? prefix, {
    int? limit,
    String? gender,
    String? originCountry,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getPrefixNamesApiV1PrefixTreeNamesPrefixGetWithHttpInfo,
              [prefix],
              {
                #limit: limit,
                #gender: gender,
                #originCountry: originCountry,
              },
            ),
            returnValue: _i4.Future<_i3.Response>.value(_FakeResponse_1(
              this,
              Invocation.method(
                #getPrefixNamesApiV1PrefixTreeNamesPrefixGetWithHttpInfo,
                [prefix],
                {
                  #limit: limit,
                  #gender: gender,
                  #originCountry: originCountry,
                },
              ),
            )),
          ) as _i4.Future<_i3.Response>);

  @override
  _i4.Future<_i2.PrefixNamesResponse?>
      getPrefixNamesApiV1PrefixTreeNamesPrefixGet(
    String? prefix, {
    int? limit,
    String? gender,
    String? originCountry,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getPrefixNamesApiV1PrefixTreeNamesPrefixGet,
              [prefix],
              {
                #limit: limit,
                #gender: gender,
                #originCountry: originCountry,
              },
            ),
            returnValue: _i4.Future<_i2.PrefixNamesResponse?>.value(),
          ) as _i4.Future<_i2.PrefixNamesResponse?>);

  @override
  _i4.Future<_i3.Response> getPrefixTreeApiV1PrefixTreeGetWithHttpInfo({
    String? prefix,
    int? maxDepth,
    String? gender,
    String? originCountry,
    num? minPopularity,
    num? maxPopularity,
    String? highlightPrefixes,
    String? highlightNameIds,
    bool? includeNames,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrefixTreeApiV1PrefixTreeGetWithHttpInfo,
          [],
          {
            #prefix: prefix,
            #maxDepth: maxDepth,
            #gender: gender,
            #originCountry: originCountry,
            #minPopularity: minPopularity,
            #maxPopularity: maxPopularity,
            #highlightPrefixes: highlightPrefixes,
            #highlightNameIds: highlightNameIds,
            #includeNames: includeNames,
          },
        ),
        returnValue: _i4.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #getPrefixTreeApiV1PrefixTreeGetWithHttpInfo,
            [],
            {
              #prefix: prefix,
              #maxDepth: maxDepth,
              #gender: gender,
              #originCountry: originCountry,
              #minPopularity: minPopularity,
              #maxPopularity: maxPopularity,
              #highlightPrefixes: highlightPrefixes,
              #highlightNameIds: highlightNameIds,
              #includeNames: includeNames,
            },
          ),
        )),
      ) as _i4.Future<_i3.Response>);

  @override
  _i4.Future<_i2.PrefixTreeResponse?> getPrefixTreeApiV1PrefixTreeGet({
    String? prefix,
    int? maxDepth,
    String? gender,
    String? originCountry,
    num? minPopularity,
    num? maxPopularity,
    String? highlightPrefixes,
    String? highlightNameIds,
    bool? includeNames,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrefixTreeApiV1PrefixTreeGet,
          [],
          {
            #prefix: prefix,
            #maxDepth: maxDepth,
            #gender: gender,
            #originCountry: originCountry,
            #minPopularity: minPopularity,
            #maxPopularity: maxPopularity,
            #highlightPrefixes: highlightPrefixes,
            #highlightNameIds: highlightNameIds,
            #includeNames: includeNames,
          },
        ),
        returnValue: _i4.Future<_i2.PrefixTreeResponse?>.value(),
      ) as _i4.Future<_i2.PrefixTreeResponse?>);

  @override
  _i4.Future<_i3.Response>
      rebuildPrefixTreeApiV1PrefixTreeRebuildPostWithHttpInfo() =>
          (super.noSuchMethod(
            Invocation.method(
              #rebuildPrefixTreeApiV1PrefixTreeRebuildPostWithHttpInfo,
              [],
            ),
            returnValue: _i4.Future<_i3.Response>.value(_FakeResponse_1(
              this,
              Invocation.method(
                #rebuildPrefixTreeApiV1PrefixTreeRebuildPostWithHttpInfo,
                [],
              ),
            )),
          ) as _i4.Future<_i3.Response>);

  @override
  _i4.Future<Object?> rebuildPrefixTreeApiV1PrefixTreeRebuildPost() =>
      (super.noSuchMethod(
        Invocation.method(
          #rebuildPrefixTreeApiV1PrefixTreeRebuildPost,
          [],
        ),
        returnValue: _i4.Future<Object?>.value(),
      ) as _i4.Future<Object?>);

  @override
  _i4.Future<_i3.Response> searchPrefixTreeApiV1PrefixTreeSearchGetWithHttpInfo(
    String? query, {
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPrefixTreeApiV1PrefixTreeSearchGetWithHttpInfo,
          [query],
          {#limit: limit},
        ),
        returnValue: _i4.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #searchPrefixTreeApiV1PrefixTreeSearchGetWithHttpInfo,
            [query],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i3.Response>);

  @override
  _i4.Future<Object?> searchPrefixTreeApiV1PrefixTreeSearchGet(
    String? query, {
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPrefixTreeApiV1PrefixTreeSearchGet,
          [query],
          {#limit: limit},
        ),
        returnValue: _i4.Future<Object?>.value(),
      ) as _i4.Future<Object?>);
}
